inhibit_all_warnings! 
use_frameworks!

def pa_pods
    pod 'GRDB.swift'
    pod 'Swifter', '~>1.4.5'
end
 
target 'PersonalAnalytics' do
    pa_pods
end
 
target 'PersonalAnalytics Dev' do
    pa_pods
end