//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDetectionTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskDetectionTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process,Category
        ///Alarms &amp; Clock,Utility
        ///APConsole,Console
        ///BC2,Developer Tool
        ///BCompare,Developer Tool
        ///BI.AutomatedTesting.vshost,IDE
        ///Bugger,Developer Tool
        ///chrome,Browser
        ///cleardescribe,Developer Tool
        ///clearexplorer,Explorer
        ///clearmrgman,Developer Tool
        ///clearprojexp,Project Explorer
        ///clearviewupdate,Developer Tool
        ///clearvtree,Developer Tool
        ///cmd,Console
        ///CodeFlow,Review
        ///Compose,ReadWrite
        ///ConsoleApp.vshost,IDE
        ///cqintsvr11,IDE
        ///defectviewer,Testing Tool
        ///devenv,IDE
        ///dllhost,Developer Tool
        ///dwm,Unknown        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessCategories {
            get {
                return ResourceManager.GetString("ProcessCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///above
        ///after
        ///again
        ///against
        ///all
        ///am
        ///an
        ///and
        ///any
        ///are
        ///aren&apos;t
        ///as
        ///at
        ///be
        ///because
        ///been
        ///before
        ///being
        ///below
        ///between
        ///both
        ///but
        ///by
        ///can&apos;t
        ///cannot
        ///could
        ///couldn&apos;t
        ///did
        ///didn&apos;t
        ///do
        ///does
        ///doesn&apos;t
        ///doing
        ///don&apos;t
        ///down
        ///during
        ///each
        ///few
        ///for
        ///from
        ///further
        ///had
        ///hadn&apos;t
        ///has
        ///hasn&apos;t
        ///have
        ///haven&apos;t
        ///having
        ///he
        ///he&apos;d
        ///he&apos;ll
        ///he&apos;s
        ///her
        ///here
        ///here&apos;s
        ///hers
        ///herself
        ///him
        ///himself
        ///his
        ///how
        ///how&apos;s
        ///i
        ///i&apos;d
        ///i&apos;ll
        ///i&apos;m
        ///i&apos;ve
        ///if
        ///in
        ///into
        ///is
        ///isn&apos;t
        ///it
        ///it&apos;s
        ///its
        ///itself
        ///let&apos;s
        ///me
        ///more
        ///most
        ///mustn&apos;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stopwords {
            get {
                return ResourceManager.GetString("stopwords", resourceCulture);
            }
        }
    }
}
