using System;
// ReSharper disable InconsistentNaming

namespace EyeCatcher.Native
{
    /// <summary>
    /// The following flag combinations are valid:
    /// 
    /// WINEVENT_INCONTEXT | WINEVENT_SKIPOWNPROCESS
    /// WINEVENT_INCONTEXT | WINEVENT_SKIPOWNTHREAD
    /// WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNPROCESS
    /// WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNTHREAD
    /// Additionally, client applications can specify WINEVENT_INCONTEXT, or WINEVENT_OUTOFCONTEXT alone.
    /// </summary>
    [Flags]
    internal enum WinEventHookFlags : uint
    {
        /// <summary>
        /// Events are ASYNC
        /// The callback function is not mapped into the address space of the process that generates the event.
        /// Because the hook function is called across process boundaries, the system must queue events.
        /// Although this method is asynchronous, events are guaranteed to be in sequential order.
        /// </summary>
        WINEVENT_OUTOFCONTEXT = 0x0000,

        /// <summary>
        /// Don't call back for events on installer's thread
        /// Prevents this instance of the hook from receiving the events that are generated by the thread that is registering this hook.
        /// </summary>
        WINEVENT_SKIPOWNTHREAD = 0x0001,
        /// <summary>
        /// Don't call back for events on installer's process
        /// Prevents this instance of the hook from receiving the events that are generated by threads in this process.
        /// This flag does not prevent threads from generating events.
        /// </summary>
        WINEVENT_SKIPOWNPROCESS = 0x0002,

        /// <summary>
        /// Events are SYNC, this causes your dll to be injected into every process
        /// The DLL that contains the callback function is mapped into the address space of the process that generates the event.
        /// With this flag, the system sends event notifications to the callback function as they occur.
        /// The hook function must be in a DLL when this flag is specified.
        /// This flag has no effect when both the calling process and the generating process are not 32-bit or 64-bit processes, or when the generating process is a console application.
        /// </summary>
        WINEVENT_INCONTEXT = 0x0004,
    }
}
